// ==============================================================================
// R.ON DRAMA STUDIO — DEMO PRODUCTION DATA (ROUND 2 EXPANDED HOLLYWOOD GRADE)
// "THE LAST ASSASSIN" — 2 Episodes, 6 Scenes, 30 Shots, Locked Master Assets
// ==============================================================================

import {
  Project,
  ProjectBible,
  ActionBible,
  Episode,
  Character,
  Location,
  Prop,
  Costume,
  ContinuityWarning,
  StoryEvent,
  StoryCheckpoint,
} from './types';

export const DEMO_PROJECT: Project = {
  id: 'proj-last-assassin',
  name: 'THE LAST ASSASSIN',
  logline: 'When a rogue supernatural syndicate weaponizes ancient martial relics in modern Neo-Kyoto, a betrayed ghost assassin must dismantle his former brotherhood before the blood moon eclipses.',
  genre: 'Action / Supernatural Thriller / Neo-Noir',
  language: '中文 / 英文',
  targetEpisodes: 10,
  episodeDuration: '5–10 分钟',
  aspectRatio: '16:9',
  visualStyle: 'A24 / Denis Villeneuve masterclass cinematic photorealism, Panavision 65mm large format anamorphic look, tactile textures, ultra-fine 35mm organic film grain',
  era: '近未来赛博古风 (Near-Future Neo-Kyoto 2049)',
  location: '新京都工业废弃港区、地下骨董金库与雨幕天台道场',
  tone: '冷峻、高压、暗黑电影质感与高烈度动作悬念',
  referenceWorks: '《John Wick 4》、《银翼杀手2049》、《边境杀手》、《影》',
  status: '制作中',
  createdAt: '2026-09-01T08:00:00Z',
  updatedAt: '2026-09-06T10:30:00Z',
};

export const DEMO_PROJECT_BIBLE: ProjectBible = {
  id: 'bible-last-assassin',
  projectId: 'proj-last-assassin',
  logline: 'When a rogue supernatural syndicate weaponizes ancient martial relics in modern Neo-Kyoto, a betrayed ghost assassin must dismantle his former brotherhood before the blood moon eclipses.',
  genre: '动作 / 悬疑 / 超自然黑色电影 (Action / Supernatural Noir)',
  theme: '荣誉契约与盲从权威的撕裂，在长生诅咒中探寻人性的尊严，暴力作为最后防线的冷酷救赎。',
  tone: '电影级冷峻克制，压迫性悬念，瞬间爆发的致命冲击力，将古老刀法与近未来机甲冷兵器熔于一炉。',
  world: '垂直分层的新京都：霓虹巨厦直插云霄，而底下是百年前废弃的工业深渊与武士血祭道场。古代遗物蕴含量子频率，被财阀用作操控傀儡杀手的神经核心。',
  era: '近未来 (Near-Future 2049)',
  location: '废弃造船厂14号仓库、60层悬挑雨夜道场、地下防震封印金库。',
  visualStyle: '好莱坞 A 级制作质感：Arri Alexa 65 大画幅摄影机，Panavision C 系列变形宽银幕镜头，物理级材质纹理，深邃阴影渐变，零低幼动漫感。',
  colorLanguage: '黑曜石纯黑为主底色，冷钨丝蓝月光与工业钠灯琥珀黄形成冷暖对冲，偶尔撕裂出克制的朱砂红血光与刀锋火花。',
  cameraLanguage: '腰平机位斯坦尼康沉稳推进、动作交锋瞬间的手持微颤、刀刃接触瞬间的 24fps 物理惯性顿挫与低角度荷兰角张力。',
  lightingLanguage: '经典伦勃朗强反差明暗对照 (8:1 光比)，天窗冷月光作为主匙光，高强度轮廓光将人物与深黑背景立体剥离，空气中浮游微尘受光散射。',
  editingRhythm: '极度克制的呼吸感静止凝滞，在 0.1 秒内骤然爆发为 24 帧超高速冷兵器击杀，收放自如。',
  directorsVision: '每一帧画面都必须具备古典莎士比亚悲剧的庄严雕塑感，同时具备当代顶级动作片（如《疾速追杀》）的物理冲击力与舞蹈般的杀伐韵律。',
  lensKitSpecs: 'Panavision C-Series Anamorphic Primes (35mm T2.3, 50mm T2.0, 85mm T2.0), 变形椭圆散景，2.39:1 画幅水平横向蓝色眩光',
  colorGradingLUT: 'Arri LogC3 转换至 Kodak Vision3 5219 胶片印片 LUT，暗部不发灰（负填充完全纯黑），高光柔和滚降 (Soft highlight roll-off)',
  lightingRatios: '8:1 主光与辅光光比 (Key-to-Fill)，强硬边缘侧逆光 (Hard Kickers)，环境体积丁达尔冷蓝光柱 (Volumetric Rayleigh Haze)',
  blockingAndStaging: '深焦三角站位场面调度 (Deep staging)：前景铁链遮挡形成窥视视角，中景主角冷峻拔刀，远景高台反派俯瞰',
  soundDesignPhilosophy: '次低音 (Sub-bass) 持续压迫氛围，强调超写实的金属拔刀啸叫 (Foley) 与雨滴敲击锌铁屋顶的空洞回响',
  updatedAt: '2026-09-06T10:30:00Z',
};

export const DEMO_ACTION_BIBLE: ActionBible = {
  id: 'action-bible-last-assassin',
  projectId: 'proj-last-assassin',
  stuntDesignStyle: '87Eleven 顶级硬派动作流派 + 日本古流居合拔刀术 + 战术近身格斗 (Tactical CQC)。严禁任何飘忽轻功假动作，所有招式兼具生体杀伤力与几何美感。',
  combatPhysics: '真实质量惯性与动量传递：每次出招有清晰的重心转移与脚掌抓地反作用力。刀剑格挡产生剧烈的金属反震，击中人体有沉重的骨骼顿挫感。',
  weaponDynamics: '折叠陨铁大马士革钢刀刃：格挡时迸射耀眼的橙红摩擦火花，刀背可顺势滑转卸力；反派纳米钢丝具柔性切割力，崩直时发出超高频蜂鸣。',
  cameraChoreography: '摄影机与动作同步编排：格挡瞬间摄影机极速微推 (Punch-in)，击退时拉远中景展现全身平衡。严格遵守 180 度轴线法则，杜绝混乱碎剪。',
  impactVelocity: '动静对撞节奏：0.5秒绝对静止的眼神对峙 → 0.2秒闪电拔刀出鞘 → 击中瞬间微顿挫（Speed Ramp）→ 收刀沉肩凝气。',
  spatialDestruction: '环境破坏力联动：刀风撕裂悬垂铁链激荡，打斗落足踩碎积水与混凝土碎渣，火花点燃地面飘散的油污，空间随打斗逐渐破碎。',
  safetyAndContinuity: '特技连贯性红线：主角服装撕裂与血渍必须逐场严格累积递进；刀剑入鞘长度与背负角度在换切镜头中保持绝对同一。',
  updatedAt: '2026-09-06T10:30:00Z',
};

export const DEMO_CHARACTERS: Character[] = [
  {
    id: 'char-ron',
    projectId: 'proj-last-assassin',
    name: 'RON (浪人)',
    role: '主角 / 幽灵刺客大师 (Protagonist / Master Assassin)',
    age: '32',
    gender: '男 (Male)',
    personality: '沉静似古井，杀意内敛，动作如外科手术般精准，只在死局已定之时开口。',
    physicalDescription: '亚裔男性，精瘦而充满爆发力的武术体魄，下颌线锋利如刀刻，双目深邃黝黑，左眉有一道细微淡色战痕。',
    hair: '乌黑微卷纹理短发，两鬓干净利落，打斗中有数缕碎发散落在冷峻额前。',
    face: '坚毅角质感面容，皮肤具真实的微出汗光泽与毛孔质感，嘴唇薄而紧抿。',
    body: '身高 182cm，站立时如古松扎根，无任何多余晃动，肌肉紧绷待发。',
    height: '182 cm (6\'0")',
    costume: '暗黑高级定制战术隐行风衣，哑光凯夫拉编织与静音碳纤维护腕，背负磁吸刀鞘。',
    signatureFeatures: '右腕缠绕微缩氏族玄蛇刺青；拔刀前拇指微推刀镡发出轻微金属“咔哒”声。',
    performanceNotes: '对峙时绝不眨眼，目光先于头部转动。出刀动作在破风前肉眼几乎无法捕捉。',
    lockedVersionId: 'char-ver-ron-3',
    states: [
      {
        id: 'ron-state-normal',
        characterId: 'char-ron',
        name: 'NORMAL',
        description: '潜行与巅峰精力状态，风衣完好无损，神色冷峻沉稳。',
        faceCondition: '白皙冷峻，微小淡色战痕，无汗无伤',
        hairCondition: '整齐微碎发，干练利落',
        costumeCondition: '全新哑光凯夫拉风衣，无刮痕破损',
        bodyCondition: '巅峰体能，无肉体创伤',
        performance: '极度沉静，呼吸均匀，潜伏如黑豹',
      },
      {
        id: 'ron-state-injured',
        characterId: 'char-ron',
        name: 'INJURED',
        description: '遭遇埋伏负伤状态，左额角有破裂血痕，左肩风衣撕裂。',
        faceCondition: '左眉骨一道新鲜血迹顺面颊流下，下颌带微量雨水泥泞',
        hairCondition: '碎发被雨水和汗水打湿贴在额前',
        costumeCondition: '左肩撕裂露出一道皮肉划伤，战术护腕有灼黑火花擦痕',
        bodyCondition: '左肩中度挫伤，移动微沉但杀力更甚',
        performance: '眼神泛着冷酷凶芒，受伤反而激发出狂暴反杀欲望',
      },
      {
        id: 'ron-state-battle-damaged',
        characterId: 'char-ron',
        name: 'BATTLE DAMAGED',
        description: '高烈度搏杀极度战损状态，风衣残破，刀镡与指节渗血。',
        faceCondition: '面部多处划痕与火药烟熏微痕，冷冽双眼血丝密布',
        hairCondition: '凌乱湿漉，血水与雨水滴落',
        costumeCondition: '战术风衣多处刀刃撕裂口，内部护甲暴露',
        bodyCondition: '内腑震荡，动作转为搏命狠辣一击必杀',
        performance: '绝境孤狼般的冷血狠厉',
      },
      {
        id: 'ron-state-exhausted',
        characterId: 'char-ron',
        name: 'EXHAUSTED',
        description: '体能临界透支状态，呼吸粗重，刀尖低垂。',
        faceCondition: '面色苍白，冷汗狂流',
        hairCondition: '极度散乱',
        costumeCondition: '浸透雨水与血迹，沉重下坠',
        bodyCondition: '体能耗尽，仅凭肌肉记忆支撑',
        performance: '粗重喘息，缓慢而致命的收割',
      }
    ],
    versions: [
      {
        id: 'char-ver-ron-1',
        characterId: 'char-ron',
        versionTag: 'V1',
        notes: '初期概念版：厚重装甲披风造型。',
        status: 'ARCHIVED',
        createdAt: '2026-09-01T09:00:00Z',
      },
      {
        id: 'char-ver-ron-2',
        characterId: 'char-ron',
        versionTag: 'V2',
        notes: '都市战术改良版：战术背心与挂绳系统。',
        status: 'SELECTED',
        createdAt: '2026-09-02T11:00:00Z',
      },
      {
        id: 'char-ver-ron-3',
        characterId: 'char-ron',
        versionTag: 'V3',
        notes: '终极主视觉参考 (Master Reference)：极致高机动隐行风衣，经典微碎发发型，哑光质感。',
        status: 'LOCKED',
        createdAt: '2026-09-03T14:30:00Z',
      },
    ],
    createdAt: '2026-09-01T08:30:00Z',
    updatedAt: '2026-09-03T14:30:00Z',
  },
  {
    id: 'char-kira',
    projectId: 'proj-last-assassin',
    name: 'KIRA (云雀)',
    role: '反派核心 / 纳米钢丝操纵者 (Antagonist / Syndicate Controller)',
    age: '27',
    gender: '女 (Female)',
    personality: '残酷优雅，病态冷血，对 Ron 怀有复杂的情感怨恨，视杀戮为编织艺术。',
    physicalDescription: '东亚女性，身形修长柔韧，高挑冷艳，肤色苍白如瓷，左眼下有一颗微小的泪痣。',
    hair: '垂腰深紫黑色姬发式直发，齐刘海，行走时如流水滑顺，没有任何杂乱。',
    face: '完美对称的冷酷鹅蛋脸，红唇如干涸血迹，双眼微挑带着猫科掠食者的轻蔑。',
    body: '身高 175cm，芭蕾舞者般的极高身体柔韧度，指关节佩戴精密钛合金神经控制戒环。',
    height: '175 cm (5\'9")',
    costume: '黑曜石光泽高开叉立领漆皮风衣，内衬暗红丝绸，隐蔽佩戴多轴微型导线轮。',
    signatureFeatures: '十指微动时，空气中闪烁几乎不可见的淡蓝纳米反光钢丝。',
    performanceNotes: '说话时语气轻柔近乎呢喃，杀人动作轻盈如芭蕾旋转，从不动怒。',
    lockedVersionId: 'char-ver-kira-2',
    versions: [
      {
        id: 'char-ver-kira-1',
        characterId: 'char-kira',
        versionTag: 'V1',
        notes: '初期概念：赛博义体假面反派。',
        status: 'ARCHIVED',
        createdAt: '2026-09-01T10:00:00Z',
      },
      {
        id: 'char-ver-kira-2',
        characterId: 'char-kira',
        versionTag: 'V2',
        notes: '已锁定主视觉参考：黑曜漆皮风衣、深紫黑直发姬发式、冷艳泪痣。',
        status: 'LOCKED',
        createdAt: '2026-09-03T16:00:00Z',
      },
    ],
    createdAt: '2026-09-01T09:30:00Z',
    updatedAt: '2026-09-03T16:00:00Z',
  },
  {
    id: 'char-marcus',
    projectId: 'proj-last-assassin',
    name: 'MARCUS / THE ARBITER (裁决者)',
    role: '幕后黑手 / 财阀武装最高统帅 (Syndicate High Arbiter)',
    age: '50',
    gender: '男 (Male)',
    personality: '威严独裁，坚信弱肉强食进化论，拥有压倒性的生化机械巨力与古典政客修养。',
    physicalDescription: '高大魁梧的混血男性，两鬓斑白，右臂与脊柱为纯手工锻造的黄铜机械外骨骼。',
    hair: '两鬓银灰平头短发，修剪极度严谨。',
    face: '苍老而坚如磐石的面庞，眼眶深陷，带有帝国上位者的不怒自威。',
    body: '身高 190cm，重装体魄，行走沉重如同战车。',
    height: '190 cm (6\'3")',
    costume: '定制重装三件套黑金西装，外覆军用重甲骨骼，胸前悬挂古老家族家徽。',
    signatureFeatures: '右手持一支点燃的古巴雪茄，机械左手轻易捏碎大理石。',
    performanceNotes: '言语迟缓深沉，低频嗓音自带威慑。',
    lockedVersionId: 'char-ver-marcus-1',
    versions: [
      {
        id: 'char-ver-marcus-1',
        characterId: 'char-marcus',
        versionTag: 'V1',
        notes: '已锁定主视觉参考：黑金西装重甲骨骼、两鬓银灰、不怒自威。',
        status: 'LOCKED',
        createdAt: '2026-09-04T09:00:00Z',
      },
    ],
    createdAt: '2026-09-02T10:00:00Z',
    updatedAt: '2026-09-04T09:00:00Z',
  },
];

export const DEMO_LOCATIONS: Location[] = [
  {
    id: 'loc-warehouse',
    projectId: 'proj-last-assassin',
    name: 'ABANDONED WAREHOUSE (14号废弃船厂仓库)',
    description: '新京都重工业区荒废三十年的造船厂核心装配仓库，濒临黑水运河，暴雨倾盆。',
    architecture: '粗野主义工业混凝土基座，高耸的锈蚀工字钢桁架与高悬的天车轨道。',
    environment: '地面布满积水凹坑，悬挂着上百根沾满机油的重型铸铁吊链，穿堂风呼啸。',
    time: 'NIGHT (深夜 23:45)',
    weather: '暴雨、雷鸣电闪透过破损天窗在室内投下刺目光斑。',
    lighting: '8:1 强反差 Chiaroscuro；高处破窗洒下冰冷月光，远处有工业琥珀色低压钠灯。',
    colorPalette: '深冷钨丝蓝、黑曜石混凝土黑、微光琥珀黄。',
    atmosphere: '刺骨潮湿、工业铁锈味、暴雨击打铁皮屋顶的空洞回响。',
    cameraNotes: '适合低角度广角仰拍以展现上百根垂挂铁链的森林感；地面水洼倒影。',
    lockedVersionId: 'loc-ver-warehouse-2',
    versions: [
      {
        id: 'loc-ver-warehouse-1',
        locationId: 'loc-warehouse',
        versionTag: 'V1',
        notes: '初期普通废弃厂房。',
        status: 'ARCHIVED',
        createdAt: '2026-09-01T12:00:00Z',
      },
      {
        id: 'loc-ver-warehouse-2',
        locationId: 'loc-warehouse',
        versionTag: 'V2',
        notes: '已锁定主场景参考：上百根工业吊链、积水反光、天窗冷月光光束。',
        status: 'LOCKED',
        createdAt: '2026-09-03T11:00:00Z',
      },
    ],
    createdAt: '2026-09-01T11:00:00Z',
    updatedAt: '2026-09-03T11:00:00Z',
  },
  {
    id: 'loc-rooftop-dojo',
    projectId: 'proj-last-assassin',
    name: 'ROOFTOP DOJO (60层雨夜天台道场)',
    description: '坐落于新京都超摩天楼顶层的悬空露天木质道场，俯瞰无尽的赛博霓虹云海。',
    architecture: '传统日式雪松木斗拱飞檐，与近未来钢化防风玻璃幕墙交融。',
    environment: '光滑的深色桧木地板覆满薄薄一层雨水，四周摆放着修剪整齐的石松盆景。',
    time: 'MIDNIGHT (午夜 01:30)',
    weather: '细雨微风，远方雷云翻滚。',
    lighting: '纸灯笼暖橙柔光与楼外巨大全息广告投影的冷青蓝电光对冲。',
    colorPalette: '桧木深褐、全息赛博青、朱红灯笼暖色。',
    atmosphere: '超脱俗世的冷寂与孤高决绝感。',
    cameraNotes: '水平滑轨全景镜头，利用雨幕倒影与边缘悬空感营造命悬一线的视觉张力。',
    lockedVersionId: 'loc-ver-dojo-1',
    versions: [
      {
        id: 'loc-ver-dojo-1',
        locationId: 'loc-rooftop-dojo',
        versionTag: 'V1',
        notes: '已锁定主场景参考：悬挑雨夜天台、桧木地板水镜反光、全息霓虹云海。',
        status: 'LOCKED',
        createdAt: '2026-09-03T14:00:00Z',
      },
    ],
    createdAt: '2026-09-02T11:00:00Z',
    updatedAt: '2026-09-03T14:00:00Z',
  },
  {
    id: 'loc-vault',
    projectId: 'proj-last-assassin',
    name: 'SUB-LEVEL VAULT (地下骨董封印金库)',
    description: '深埋于地下百米的财阀核心量子防震金库，保管着百年前各宗门被掠夺的冷兵器圣物。',
    architecture: '六角形厚重钛合金防爆墙面，几何对称的防震液压立柱。',
    environment: '中心是一座悬浮的电磁隔离台，周围环绕着红外线警报光网与极低温白雾。',
    time: 'NIGHT (凌晨 03:00)',
    weather: '密闭地下，人工低温制冷雾气流淌。',
    lighting: '冷白极简工业泛光，警报红线切割空间，电磁台发出幽微翠绿光芒。',
    colorPalette: '钛银冷灰、激光纯红、电磁荧光绿。',
    atmosphere: '高科技神圣感与致命防卫机关的死寂压迫。',
    cameraNotes: '对称构图，慢速推拉镜头展现空间的机械冰冷与几何秩序。',
    lockedVersionId: 'loc-ver-vault-1',
    versions: [
      {
        id: 'loc-ver-vault-1',
        locationId: 'loc-vault',
        versionTag: 'V1',
        notes: '已锁定主参考：钛合金六角金库、电磁悬浮圣台、极低温白雾。',
        status: 'LOCKED',
        createdAt: '2026-09-04T12:00:00Z',
      },
    ],
    createdAt: '2026-09-03T09:00:00Z',
    updatedAt: '2026-09-04T12:00:00Z',
  },
];

export const DEMO_PROPS: Prop[] = [
  {
    id: 'prop-katana',
    projectId: 'proj-last-assassin',
    name: 'ANCIENT KATANA (折叠龙文大马士革武士刀)',
    description: 'Ron 家传百年的镇派古刃，采用陨铁与高碳钢万层折叠锻打，刃纹如流动的黑龙波浪。',
    material: '陨铁大马士革高碳钢、黑色珍珠鱼皮柄、暗金战损龙形刀镡。',
    color: '刀刃为哑光灰黑色微带暗蓝，反光时浮现水波状互锁纹理。',
    size: '全长 103cm，刃长 73cm，刀鞘覆哑光黑漆。',
    function: '主角终极处刑兵刃，刀身坚韧至极，能直接斩断高频机械钢缆。',
    storyImportance: '第一核心主道具 (Hero Prop)，宗派传承与誓约血契的具象化象征。',
    lockedVersionId: 'prop-ver-katana-1',
    versions: [
      {
        id: 'prop-ver-katana-1',
        propId: 'prop-katana',
        versionTag: 'V1',
        notes: '已锁定主参考：黑龙鳞纹大马士革刃、黑色鱼皮刀柄、暗金龙镡。',
        status: 'LOCKED',
        createdAt: '2026-09-03T10:00:00Z',
      },
    ],
    createdAt: '2026-09-01T14:00:00Z',
    updatedAt: '2026-09-03T10:00:00Z',
  },
  {
    id: 'prop-chains',
    projectId: 'proj-last-assassin',
    name: 'NANO-METALLIC CHAINS (反派悬吊纳米控制钢链)',
    description: '仓库中高挂的重型工业铁链，内部被 Kira 植入纳米级超导微丝，可在瞬间形成夺命绞杀网。',
    material: '铸铁环扣与发光蓝色纳米导线复合编织。',
    color: '锈蚀铸铁黑配微弱蓝光。',
    size: '每节链环长 15cm，悬垂总长达数十米。',
    function: '大面积环境杀戮机关与格斗阻挡物。',
    storyImportance: '第一集动作大戏核心舞台道具。',
    lockedVersionId: 'prop-ver-chains-1',
    versions: [
      {
        id: 'prop-ver-chains-1',
        propId: 'prop-chains',
        versionTag: 'V1',
        notes: '已锁定主参考：锈蚀铸铁外表、通电瞬间蓝光微震。',
        status: 'LOCKED',
        createdAt: '2026-09-03T12:00:00Z',
      },
    ],
    createdAt: '2026-09-02T13:00:00Z',
    updatedAt: '2026-09-03T12:00:00Z',
  },
  {
    id: 'prop-relic-box',
    projectId: 'proj-last-assassin',
    name: 'CYBERNETIC RELIC BOX (量子频率神龛核心箱)',
    description: '承载宗门远古神经控制芯片与量子调频密钥的密封箱，表面雕刻有微型八卦电路。',
    material: '航空级阳极氧化钛金属与防电磁高聚物。',
    color: '哑光深空灰与发光翠绿电路纹路。',
    size: '30cm x 20cm x 15cm，手提式。',
    function: '剧情核心麦高芬 (MacGuffin)，能够操控全城暗杀傀儡的思维中枢。',
    storyImportance: '全剧主线争夺焦点。',
    lockedVersionId: 'prop-ver-box-1',
    versions: [
      {
        id: 'prop-ver-box-1',
        propId: 'prop-relic-box',
        versionTag: 'V1',
        notes: '已锁定主参考：深空灰八卦电路线条、翠绿荧光锁孔。',
        status: 'LOCKED',
        createdAt: '2026-09-04T11:00:00Z',
      },
    ],
    createdAt: '2026-09-03T10:00:00Z',
    updatedAt: '2026-09-04T11:00:00Z',
  },
];

export const DEMO_COSTUMES: Costume[] = [
  {
    id: 'costume-ron-tactical',
    projectId: 'proj-last-assassin',
    characterId: 'char-ron',
    characterName: 'RON',
    name: 'TACTICAL COMBAT COAT (Ron 暗黑隐形战术风衣)',
    description: '极度修身的战术长款风衣，立领设计，肩部内嵌柔性防刺凯夫拉护板。',
    material: '纳米碳纤维哑光织物，防雨涂层，具备光学吸光属性。',
    color: '暗黑炭黑 (Charcoal Black)，无任何反光 Logo。',
    accessories: '磁吸式背部刀鞘扣具，右小臂静音快速收束带。',
    shoes: '静音软底凯夫拉战术靴，踩水无声。',
    condition: '崭新完好，隐秘行动状态。',
    lockedVersionId: 'cost-ver-ron-1',
    versions: [
      {
        id: 'cost-ver-ron-1',
        costumeId: 'costume-ron-tactical',
        versionTag: 'V1',
        notes: '已锁定主参考：立领炭黑风衣、背部磁吸刀鞘、静音战靴。',
        status: 'LOCKED',
        createdAt: '2026-09-03T14:00:00Z',
      },
    ],
    createdAt: '2026-09-01T15:00:00Z',
    updatedAt: '2026-09-03T14:00:00Z',
  },
  {
    id: 'costume-kira-obsidian',
    projectId: 'proj-last-assassin',
    characterId: 'char-kira',
    characterName: 'KIRA',
    name: 'OBSIDIAN CONTROLLER TRENCH (Kira 黑曜漆皮风衣)',
    description: '高级定制的修身立领漆皮风衣，高开叉下摆方便腿法施展，袖口暗藏导线轮。',
    material: '高光暗黑小羊皮漆皮，内衬暗红丝绸。',
    color: '深渊光泽黑配猩红内里。',
    accessories: '十指神经控制器钛合金戒环，银质耳骨通讯器。',
    shoes: '强化钛金细高跟战斗短靴。',
    condition: '高贵一尘不染的顶级掠食者姿态。',
    lockedVersionId: 'cost-ver-kira-1',
    versions: [
      {
        id: 'cost-ver-kira-1',
        costumeId: 'costume-kira-obsidian',
        versionTag: 'V1',
        notes: '已锁定主参考：立领漆皮、暗红丝绸内衬、戒环发光。',
        status: 'LOCKED',
        createdAt: '2026-09-03T17:00:00Z',
      },
    ],
    createdAt: '2026-09-03T16:30:00Z',
    updatedAt: '2026-09-03T17:00:00Z',
  },
  {
    id: 'costume-arbiter-suit',
    projectId: 'proj-last-assassin',
    characterId: 'char-marcus',
    characterName: 'MARCUS / THE ARBITER',
    name: 'ARBITER CEREMONIAL EXOSUIT (裁决者礼仪重装外骨骼)',
    description: '高级手工定制黑色双排扣羊毛西服，外覆纯黄铜精密液压战术机械骨骼。',
    material: '英式精纺纯羊毛，镀钛黄铜合金，真皮战术背带。',
    color: '冷黑色西服配亮金黄铜机械骨骼。',
    accessories: '怀表金链，机械手掌能量指示灯。',
    shoes: '手工定制牛津皮鞋，鞋跟包覆钢板。',
    condition: '庄重威严，极度奢华与暴力的结合体。',
    lockedVersionId: 'cost-ver-arbiter-1',
    versions: [
      {
        id: 'cost-ver-arbiter-1',
        costumeId: 'costume-arbiter-suit',
        versionTag: 'V1',
        notes: '已锁定主参考：双排扣西服、黄铜机械骨骼、威严奢华。',
        status: 'LOCKED',
        createdAt: '2026-09-04T10:00:00Z',
      },
    ],
    createdAt: '2026-09-04T09:30:00Z',
    updatedAt: '2026-09-04T10:00:00Z',
  },
];

// Helper to generate 5 shots for demo scenes
function createDemoShots(sceneId: string, prefix: string, subject: string, location: string): any[] {
  return [
    {
      id: `${sceneId}-shot-1`,
      sceneId,
      shotNumber: 1,
      shotType: 'Wide Shot',
      framing: 'Rule of thirds',
      cameraAngle: 'Low Angle',
      lens: '35mm',
      cameraMovement: 'Push In',
      cameraSpeed: 'deliberate',
      screenDirection: 'Left → Right',
      cameraSide: 'A',
      eyeLine: 'Screen Right',
      pacing: 'Normal',
      transitionIn: 'Cut',
      transitionOut: 'Cut',
      subject: `${subject} establishing`,
      action: `${subject} moves forward with calculated tactical rhythm inside ${location}.`,
      performance: 'Focused, stoic, alert.',
      blocking: 'Deep multi-plane triangle staging.',
      environment: location,
      lighting: '8:1 contrast chiaroscuro with cold rim light.',
      atmosphere: 'Suspended airborne dust, volumetric light shafts.',
      composition: 'Golden ratio lower third.',
      depth: 'Deep cinematic focus.',
      visualEffects: 'Micro-dust particles.',
      transition: 'Cut',
      duration: '4s',
      sound: 'Heavy footsteps, ambient drone.',
      directorNotes: 'Establish physical spatial gravity and tension.',
      promptAvoid: 'Do not change facial identity. Do not change hairstyle. Do not redesign the location.',
      sortOrder: 1,
      productionStatus: 'SHOT DESIGNED',
      takes: [
        {
          id: `take-${sceneId}-1-1`,
          shotId: `${sceneId}-shot-1`,
          takeNumber: 1,
          videoUrl: 'blob:demo-placeholder-take-1',
          notes: '[DEMO PLACEHOLDER] 摄影机推入节奏精准，空间纵深感极强。',
          status: 'SELECTED',
          createdAt: '2026-09-04T12:00:00Z',
        }
      ],
      selectedTakeId: `take-${sceneId}-1-1`,
    },
    {
      id: `${sceneId}-shot-2`,
      sceneId,
      shotNumber: 2,
      shotType: 'Medium Close Up',
      framing: 'Eye Level',
      cameraAngle: 'Eye-level',
      lens: '50mm',
      cameraMovement: 'Tracking',
      cameraSpeed: 'steady',
      screenDirection: 'Left → Right',
      cameraSide: 'A',
      eyeLine: 'Screen Right',
      pacing: 'Normal',
      transitionIn: 'Cut',
      transitionOut: 'Cut',
      subject: `${subject} posture & hand`,
      action: `${subject} adjusts weapon grip as dynamic shadows cross the face.`,
      performance: 'Sharp gaze shift, zero wasted motion.',
      blocking: 'Isolated in center frame.',
      environment: location,
      lighting: 'Hard edge kicker light on jawline.',
      atmosphere: 'Ground mist rising.',
      composition: 'Off-center character portrait.',
      depth: 'Shallow focal depth, background soft blur.',
      visualEffects: 'Lens anamorphic flare.',
      transition: 'Cut',
      duration: '3s',
      sound: 'Leather friction, weapon mechanical click.',
      directorNotes: 'Intensify emotional stakes.',
      promptAvoid: 'Do not change facial identity. Preserve eye line vector.',
      sortOrder: 2,
      productionStatus: 'SHOT DESIGNED',
      takes: [
        {
          id: `take-${sceneId}-2-1`,
          shotId: `${sceneId}-shot-2`,
          takeNumber: 1,
          videoUrl: 'blob:demo-placeholder-take-2',
          notes: '[DEMO PLACEHOLDER] 眼神与微出汗面部质感优秀。',
          status: 'SELECTED',
          createdAt: '2026-09-04T13:00:00Z',
        }
      ],
      selectedTakeId: `take-${sceneId}-2-1`,
    },
    {
      id: `${sceneId}-shot-3`,
      sceneId,
      shotNumber: 3,
      shotType: 'Close Up',
      framing: 'Tight',
      cameraAngle: 'Dutch Angle',
      lens: '85mm',
      cameraMovement: 'Steadicam',
      cameraSpeed: 'accelerating',
      screenDirection: 'Toward Camera',
      cameraSide: 'Neutral',
      eyeLine: 'Camera',
      pacing: 'Fast',
      transitionIn: 'Cut',
      transitionOut: 'Cut',
      subject: `${subject} eyes and weapon tsuba`,
      action: 'Steel blade glints as sudden vibration ripples through the environment.',
      performance: 'Lethal micro-expression.',
      blocking: 'Extreme close foreground slice.',
      environment: location,
      lighting: 'Specular streak flare along blade edge.',
      atmosphere: 'Condensation drips.',
      composition: 'Diagonal Dutch tilt.',
      depth: 'Razor thin focal plane.',
      visualEffects: 'Prismatic blade gleam.',
      transition: 'Cut',
      duration: '2s',
      sound: 'High frequency resonance hum.',
      directorNotes: 'Auditory and visual pre-contact cue.',
      promptAvoid: 'Do not alter Damascus blade texture or ray-skin handle.',
      sortOrder: 3,
      productionStatus: 'SHOT DESIGNED',
    },
    {
      id: `${sceneId}-shot-4`,
      sceneId,
      shotNumber: 4,
      shotType: 'Tracking Shot',
      framing: 'Waist level',
      cameraAngle: 'Low Angle',
      lens: '35mm',
      cameraMovement: 'Tracking',
      cameraSpeed: 'kinetic burst',
      screenDirection: 'Left → Right',
      cameraSide: 'A',
      eyeLine: 'Screen Right',
      pacing: 'Impact',
      transitionIn: 'Action Match',
      transitionOut: 'Cut',
      subject: `${subject} kinetic strike / parry`,
      action: `${subject} launches into explosive combat maneuver, parrying incoming threat with sparks spraying.`,
      performance: 'Full body inertia, heavy physical mass acceleration.',
      blocking: 'Dynamic lateral charge.',
      environment: location,
      lighting: 'Friction spark flash illuminating faces.',
      atmosphere: 'Sparks bouncing across concrete.',
      composition: 'Kinetic vector leading right to left.',
      depth: 'Deep dynamic staging.',
      visualEffects: 'Metal contact sparks and debris flying.',
      transition: 'Cut',
      duration: '3s',
      sound: 'Bone-shattering impact, steel crash.',
      directorNotes: '87Eleven stunt execution with speed ramp.',
      promptAvoid: 'Maintain physical inertia. Do not fly or hang on wirework.',
      sortOrder: 4,
      productionStatus: 'SHOT DESIGNED',
    },
    {
      id: `${sceneId}-shot-5`,
      sceneId,
      shotNumber: 5,
      shotType: 'Extreme Wide Shot',
      framing: 'Grand scale',
      cameraAngle: 'High Angle',
      lens: '24mm',
      cameraMovement: 'Pull Back',
      cameraSpeed: 'slow',
      screenDirection: 'Static',
      cameraSide: 'Neutral',
      eyeLine: 'Object',
      pacing: 'Slow',
      transitionIn: 'Cut',
      transitionOut: 'Dissolve',
      subject: `${subject} standing victorious in aftermath`,
      action: `${subject} recovers stance as defeated opponents collapse into the dark mist.`,
      performance: 'Breathing stillness, slow weapon reset.',
      blocking: 'Solitary figure amidst shattered environment.',
      environment: location,
      lighting: 'Fading spark illumination returning to cold moonlight.',
      atmosphere: 'Lingering smoke and water droplets.',
      composition: 'Monumental symmetrical architecture.',
      depth: 'Infinite perspective vanishing point.',
      visualEffects: 'Environmental debris settle.',
      transition: 'Smash Cut',
      duration: '5s',
      sound: 'Wind howl, distant thunder.',
      directorNotes: 'Epic tableau transition to next sequence.',
      promptAvoid: 'Do not remove fallen enemy silhouettes or smoke density.',
      sortOrder: 5,
      productionStatus: 'SHOT DESIGNED',
    },
  ];
}

export const DEMO_EPISODES: Episode[] = [
  {
    id: 'ep-01',
    projectId: 'proj-last-assassin',
    episodeNumber: 1,
    title: 'SHADOW RECKONING (暗影宿怨)',
    logline: '浪人 Ron 潜入废弃的造船厂仓库寻找失窃的宗门圣物，却直接踏入由昔日同门师妹 Kira 精密布设的钢丝死局。',
    synopsis: '为追寻被劫走的家传古刃，Ron 来到暴雨笼罩的新京都运河 14 号船坞。原以为是一次隐秘潜入，却在深入仓库后发现所有退路已被悬挂的铁链死死封死，Kira 站在上空钢梁俯瞰，五名被神经操纵的傀儡杀手随之从天而降。',
    runtime: '8 分钟 (480s)',
    status: '制作中',
    directorNotes: '从开场就奠定好莱坞大片格调：极度克制的呼吸感几何构图逐渐收紧，随后在 0.1 秒内引爆惊心动魄的冷兵器交锋。打斗前必须有足够纯粹的死寂。',
    sortOrder: 1,
    scenes: [
      {
        id: 'scene-01-01',
        episodeId: 'ep-01',
        sceneNumber: 1,
        sceneTitle: 'INT. ABANDONED WAREHOUSE - NIGHT (废弃造船厂14号仓库 — 夜)',
        intExt: 'INT',
        locationName: 'ABANDONED WAREHOUSE',
        timeOfDay: 'NIGHT 夜晚',
        characters: ['RON (浪人)', 'KIRA (云雀)'],
        props: ['ANCIENT KATANA', 'NANO-METALLIC CHAINS'],
        costumes: ['TACTICAL COMBAT COAT (RON)'],
        storyPurpose: '瞬间抓住观众眼球，树立主角顶级特工般的宗师身手与冷峻威压，同时揭开反派恐怖的神经控制科技。',
        emotion: '冰冷死寂、雷霆杀意、刀锋悬于发丝之紧绷感。',
        conflict: 'Ron 陷入被多层工业钢缆与傀儡包围的绝命陷阱。',
        duration: '150s (2m 30s)',
        directorNotes: '强反差明暗对照。天窗泼洒而下的冷月光为全场基调，每一次兵刃出鞘都必须如雷霆破空。',
        scriptExcerpt: `场次 01. 废弃造船厂仓库 — 夜 (INT. ABANDONED WAREHOUSE - NIGHT)

RON（32岁，亚裔男性，身着暗黑战术隐形风衣）悄无声息地踩过雨水浸透的混凝土地面。
上方悬挂的数百根重型工业吊车铁链在穿堂风中发出冷硬的金属碰撞声。

远处高处的钢梁走廊上，一个妖娆而致命的身影浮现——
KIRA 手指微微转动纳米控制戒指，冷冷注视着下方的 Ron。

RON 手按在古老武士刀的刀柄上，拇指轻推，寒光微露。

KIRA
（轻声冷笑）
你不该从坟墓里爬回来的，师兄。

RON
东西在哪里？

KIRA
在这座城市的每一具尸体里。

刹那间，数百根纳米钢链从四面八方尖啸刺向 Ron！`,
        directorScenePurpose: '将观众直接拉入高概念动作宇宙，证明这不是普通街头乱斗，而是一场宗师级高智商杀伐棋局。',
        directorEmotionalArc: '精密冷峻潜入 → 发现圈套的瞬间冷静 → 爆发雷霆斩杀。',
        directorAudienceExperience: '屏息凝神，感到刺骨的工业冰冷与悬挂铁链的逼仄压迫，直至第一刀引爆视听感官。',
        directorPacing: '催眠般压迫的慢速推移，骤然撕裂为 24 帧超音速招式互换。',
        directorVisualStrategy: '极低机位强化穹顶压迫感与垂直铁链阵列；变形宽银幕椭圆光斑与雨滴反光。',
        directorPerformanceDirection: 'Ron 全身零多余晃动，眼神锁定先于头部转动；Kira 优雅玩弄指环，如猫戏老鼠。',
        directorCameraStrategy: '斯坦尼康稳定腰平推进；接触格挡瞬间手持微冲，浅景深虚化背景钢梁。',
        directorLightingStrategy: '单束天窗冷蓝月光作为主匙光，单盏暖黄吊灯提供侧逆轮廓光，雨水地面提供高光倒影。',
        directorSoundDirection: '次低音持续压迫，雨滴击打锌铁屋顶空洞回响，刀锋拔鞘高频微鸣。',
        directorTransition: '刀刃雷霆碰撞瞬间重击跳切至片名卡。',
        productionStatus: 'PROMPT READY',
        sortOrder: 1,
        beats: [
          {
            id: 'beat-01',
            sceneId: 'scene-01-01',
            beatNumber: 1,
            description: 'Ron 穿透破损墙体潜入，凝视月光下静止垂挂的重型工业铁链。',
            characters: 'RON (浪人)',
            action: '稳健缓步推进，右手始终虚按刀柄。',
            emotionalShift: '冷静战术评估。',
            sortOrder: 1,
          },
          {
            id: 'beat-02',
            sceneId: 'scene-01-01',
            beatNumber: 2,
            description: '高空起重机悬梁传来轻微冷笑，Kira 手持神经核心符牌踱步至铁网边缘。',
            characters: 'RON (浪人), KIRA (云雀)',
            action: 'Ron 不动如山，Kira 手指微屈活动微米钢丝。',
            emotionalShift: '确认为熟人设下的死局。',
            sortOrder: 2,
          },
        ],
        shots: [
          {
            id: 'shot-01-01-01',
            sceneId: 'scene-01-01',
            shotNumber: 1,
            shotType: 'Medium Wide Shot',
            framing: 'Eye Level',
            cameraAngle: 'Low Angle',
            lens: '35mm',
            cameraMovement: 'Push In',
            cameraSpeed: 'deliberate',
            subject: 'RON (浪人)',
            action: 'Ron steps across rain-slicked concrete floor, water rippling under tactical boots. Suspended chains hang motionless above him.',
            performance: 'Stoic, measured breathing, gaze locked onto distant warehouse shadow, zero wasted movement.',
            blocking: 'Centered in cavernous space, flanked by monolithic rusted pillars.',
            environment: 'Industrial brutalism, rusted steel pillars, shafts of cold cyan moonlight piercing through airborne dust.',
            lighting: 'Cool blue moonlight key from broken skylight (8:1 contrast), amber rim light from distant industrial pendant.',
            atmosphere: 'Dense floating dust motes, ground mist, cold condensation dripping.',
            composition: 'Ron centered in lower third, massive rusted hoist chain framing the right edge.',
            depth: 'Deep cinematic focus revealing cavernous warehouse backdrop.',
            visualEffects: 'Volumetric Rayleigh light rays through moisture.',
            transition: 'Cut',
            duration: '4s',
            dialogue: '',
            sound: 'Hollow dripping of rain on zinc roof, distant sub-bass Neo-Kyoto drone.',
            directorNotes: 'Iconic cinematic hero introduction establishing the physical weight of the world.',
            sortOrder: 1,
            isPromptLocked: true,
            productionStatus: 'VIDEO APPROVED',
            prompts: [
              {
                id: 'prompt-demo-1',
                shotId: 'shot-01-01-01',
                versionTag: 'V1',
                promptUniversal: 'Cinematic master shot, Ron (Master Assassin V3 locked) walking into industrial warehouse under cold cyan moonlight, Panavision 35mm anamorphic, 8:1 chiaroscuro.',
                promptGoogleFlow: 'Camera tracking low angle pushing in. Ron walking in warehouse. Rain reflections, cold cyan backlight. --shutter 180 --lens 35mm',
                promptDreamina: 'Hollywood action still, Ron walking through mist in brutalist warehouse, Arri Alexa 65, 8k, photorealistic.',
                isLocked: true,
                createdAt: '2026-09-04T10:15:00Z',
              },
              {
                id: 'prompt-demo-2',
                shotId: 'shot-01-01-01',
                versionTag: 'V2',
                promptUniversal: 'Cinematic master shot, Ron (Master Assassin V3 locked) walking into industrial warehouse under cold cyan moonlight, Panavision 50mm anamorphic, high contrast chiaroscuro, intensified rain atmosphere and neon cyan halo.',
                promptGoogleFlow: 'Camera tracking low angle pushing in smoothly. Ron walking into damp warehouse. Rain reflections, cold cyan backlight, heavy mist. --shutter 180 --lens 50mm --motion 4',
                promptDreamina: 'Hollywood action still, Ron walking through dense mist in brutalist warehouse, Panavision C-Series 50mm, Arri Alexa 65, cinematic grain, photorealistic.',
                isLocked: false,
                status: 'ACTIVE',
                changeReason: 'Adjusted focal length from 35mm to 50mm to intensify character presence and atmospheric rain reflections.',
                lengthMode: 'Standard',
                createdAt: '2026-09-05T11:20:00Z',
              },
            ],
            activePromptVersion: 'V2',
            takes: [
              {
                id: 'take-01-01-01-1',
                shotId: 'shot-01-01-01',
                takeNumber: 1,
                videoUrl: 'blob:demo-placeholder-take-1',
                notes: '[DEMO PLACEHOLDER] 导演确认主剪辑版本：步伐节奏精准，反光质感极佳。',
                status: 'SELECTED',
                createdAt: '2026-09-05T16:00:00Z',
              },
              {
                id: 'take-01-01-01-2',
                shotId: 'shot-01-01-01',
                takeNumber: 2,
                videoUrl: 'blob:demo-placeholder-take-2',
                notes: '[DEMO PLACEHOLDER] 备选推镜速度稍慢版本。',
                status: 'REVIEW',
                createdAt: '2026-09-05T16:30:00Z',
              },
            ],
            selectedTakeId: 'take-01-01-01-1',
          },
          {
            id: 'shot-01-01-02',
            sceneId: 'scene-01-01',
            shotNumber: 2,
            shotType: 'Close Up',
            framing: 'Eye Level',
            cameraAngle: 'Low Angle',
            lens: '85mm',
            cameraMovement: 'Tracking',
            cameraSpeed: 'steady',
            subject: "RON'S EYES & KATANA TSUBA",
            action: "Ron's thumb gently flicks the ancient katana tsuba, releasing the folded Damascus blade 2cm with a crisp metallic click.",
            performance: 'Absolute calm, surgical eye focus, micro-expression of calculated lethality.',
            blocking: 'Tight macro framing, background completely extinguished.',
            environment: 'Pitch-black industrial background dissolving into anamorphic oval bokeh.',
            lighting: 'Razor-sharp specular edge rim light catching the wave hamon on the exposed steel blade.',
            atmosphere: 'Floating dust motes illuminated by rim light.',
            composition: 'Extreme macro focus on thumb contact with dragon-engraved bronze tsuba.',
            depth: 'Super shallow depth of field, background completely blurred.',
            visualEffects: 'Prismatic lens glint on polished steel edge.',
            transition: 'Cut',
            duration: '3s',
            dialogue: '',
            sound: 'Loud crisp metallic *shing-click* resonant echo.',
            directorNotes: 'Signature gesture of the series. The sound must precede visual reveal.',
            sortOrder: 2,
            productionStatus: 'PROMPT READY',
          },
          {
            id: 'shot-01-01-03',
            sceneId: 'scene-01-01',
            shotNumber: 3,
            shotType: 'Extreme Wide Shot',
            framing: 'High Angle',
            cameraAngle: 'High Angle',
            lens: '24mm',
            cameraMovement: 'Crane',
            cameraSpeed: 'slow',
            subject: 'KIRA ON CRANE GANTRY LOOKING DOWN AT RON',
            action: 'Kira steps to the edge of the elevated steel crane catwalk 15 meters above Ron, silhouette framed by neon rain outside.',
            performance: 'Predatory elegance, tilted head, fingers flexing ring-mounted wire controllers.',
            blocking: 'Vertical dominance from high gantry.',
            environment: 'Upper cavernous gantry of warehouse, industrial chains crisscrossing the abyss.',
            lighting: 'Backlit silhouette with rim light from neon billboard outside broken skylight.',
            atmosphere: 'Swirling industrial exhaust steam.',
            composition: "God's eye view looking down past Kira's obsidian leather coat to isolated Ron on the wet floor below.",
            depth: 'Extreme vertical scale, vertigo sensation.',
            visualEffects: 'Rain streaks running down broken glass skylight panes.',
            transition: 'Cut',
            duration: '4s',
            dialogue: '"You should have stayed buried, Ron."',
            sound: "Kira's mocking voice reverberating through warehouse acoustics.",
            directorNotes: 'Establish vertical predator-prey dynamics before explosive action starts.',
            sortOrder: 3,
            productionStatus: 'PROMPT READY',
          },
          {
            id: 'shot-01-01-04',
            sceneId: 'scene-01-01',
            shotNumber: 4,
            shotType: 'Medium Shot',
            framing: 'Eye Level',
            cameraAngle: 'Dutch Angle',
            lens: '50mm',
            cameraMovement: 'Tracking',
            cameraSpeed: 'fast',
            subject: 'RON DRAWS BLADE AS WIRES STRIKE (ACTION CLIMAX)',
            action: 'Ron draws the Ancient Katana in an explosive rotational arc, parrying three glowing micro-wires that spark violently off the steel with realistic momentum.',
            performance: 'Explosive kinetic reaction, absolute body control and rotational power, grounded footwork.',
            blocking: 'Dynamic diagonal rotational pivot.',
            environment: 'Warehouse floor illuminated by brilliant shower of orange parry friction sparks.',
            lighting: 'Dynamic orange spark flash illuminating Ron\'s face in pitch darkness.',
            atmosphere: 'Sparks bouncing across wet concrete floor, ozone smoke.',
            composition: '12-degree Dutch tilt, diagonal kinetic vector.',
            depth: 'Blade slicing through midground plane.',
            visualEffects: 'Photorealistic metal friction sparks and wire deflection trajectory.',
            transition: 'Cut',
            duration: '2s',
            dialogue: '',
            sound: 'Screeching metallic deflection impact, sub-bass thump.',
            directorNotes: 'Speed ramp: normal speed on draw, micro-slowdown on wire contact, snap back to normal.',
            sortOrder: 4,
            productionStatus: 'PROMPT READY',
          },
          {
            id: 'shot-01-01-05',
            sceneId: 'scene-01-01',
            shotNumber: 5,
            shotType: 'Over The Shoulder',
            framing: 'Low Angle',
            cameraAngle: 'Low Angle',
            lens: '35mm',
            cameraMovement: 'Push In',
            cameraSpeed: 'deliberate',
            subject: 'RON FACING AMBUSH THROUGH CHAINS',
            action: 'Ron stands in low combat stance, katana leveled at waist height, watching five masked puppet assassins descend on swinging hoist chains.',
            performance: 'Unwavering stance, calculating trajectory of all five incoming threats.',
            blocking: 'Ron foreground anchor, threats converging in deep background.',
            environment: 'Chains swinging violently, casting shifting lattice shadows across the wet floor.',
            lighting: 'Flickering sodium light overhead creating rhythmic stroboscopic shadow play.',
            atmosphere: 'Heavy steam venting from floor pipe.',
            composition: "Ron's shoulder in sharp silhouette left, descending threats converging in center.",
            depth: 'Foreground silhouette to deep midground descending figures.',
            visualEffects: 'Steam vortex around Ron\'s boots.',
            transition: 'Smash Cut',
            duration: '3s',
            dialogue: '',
            sound: 'Heavy iron links clanging, accelerating heartbeat drone.',
            directorNotes: 'Cliffhanger freeze-frame shot before kinetic brawl sequence begins.',
            sortOrder: 5,
            productionStatus: 'PROMPT READY',
          },
        ],
        createdAt: '2026-09-02T10:00:00Z',
        updatedAt: '2026-09-04T12:00:00Z',
      },
      {
        id: 'scene-01-02',
        episodeId: 'ep-01',
        sceneNumber: 2,
        sceneTitle: 'EXT. INDUSTRIAL DOCKLANDS - RAIN / NIGHT (运河码头外围雨夜潜行 — 夜)',
        intExt: 'EXT',
        locationName: 'ABANDONED WAREHOUSE PERIMETER',
        timeOfDay: 'NIGHT 夜晚',
        characters: ['RON (浪人)'],
        props: ['ANCIENT KATANA'],
        costumes: ['TACTICAL COMBAT COAT (RON)'],
        storyPurpose: 'Ron 突围至暴雨码头，战术规避警用无人机热成像扫描，确认圣物调频信号来源。',
        emotion: '紧迫、战术规避、冷静压迫。',
        conflict: '避开天上巡逻机高亮探照灯与地面生化猎犬搜捕。',
        duration: '105s (1m 45s)',
        directorNotes: '暴雨如注，沥青地面霓虹倒影，探照灯横扫。',
        scriptExcerpt: `场次 02. 运河码头外围雨夜潜行 — 夜 (EXT. INDUSTRIAL DOCKLANDS - NIGHT)
Ron 翻出仓库铁栅栏，跃入泥泞冰冷的运河码头。
三架警用无人机从上方云层俯冲，刺目的冷白探照灯光柱在大地来回扫射。
Ron 压低重心，紧贴集装箱阴影疾速穿行。`,
        directorScenePurpose: '从室内近战杀伐转换为室外潮湿潜行。',
        directorEmotionalArc: '肾上腺素飙升后回归沉寂。',
        directorAudienceExperience: '心跳加速的躲避紧张感。',
        directorPacing: '中速快切。',
        directorVisualStrategy: '霓虹雨水光斑，冷青色逆光。',
        directorPerformanceDirection: '低姿态潜行，时刻警惕屋顶。',
        directorCameraStrategy: '肩扛手持跟拍奔跑。',
        directorLightingStrategy: '无人机高光探照灯刺破雨幕。',
        directorSoundDirection: '倾盆暴雨白噪音与低空旋翼啸叫。',
        directorTransition: '渐隐入阴影。',
        productionStatus: 'SHOT DESIGNED',
        sortOrder: 2,
        shots: createDemoShots('scene-01-02', 'sc02', 'Ron in rain', 'Industrial Docklands'),
        createdAt: '2026-09-02T11:00:00Z',
        updatedAt: '2026-09-03T10:00:00Z',
      },
      {
        id: 'scene-01-03',
        episodeId: 'ep-01',
        sceneNumber: 3,
        sceneTitle: 'INT. WAREHOUSE UPPER CATWALK - NIGHT (起重机悬梁终局对峙 — 夜)',
        intExt: 'INT',
        locationName: 'ABANDONED WAREHOUSE',
        timeOfDay: 'NIGHT 夜晚',
        characters: ['RON (浪人)', 'KIRA (云雀)'],
        props: ['ANCIENT KATANA', 'NANO-METALLIC CHAINS'],
        costumes: ['TACTICAL COMBAT COAT (RON)', 'OBSIDIAN CONTROLLER TRENCH (KIRA)'],
        storyPurpose: 'Ron 逆势登顶高空悬梁，直面 Kira，彻底打碎反派的控制网络，获悉幕后财阀主谋。',
        emotion: '决绝、同门羁绊断裂之痛。',
        conflict: '高空狭窄铁桥死战，悬空失足即粉身碎骨。',
        duration: '180s (3m)',
        directorNotes: '高空狂风呼啸，铁链如狂蟒暴舞。',
        scriptExcerpt: `场次 03. 起重机悬梁终局对峙 — 夜 (INT. WAREHOUSE UPPER CATWALK - NIGHT)
Ron 踏碎钢阶跃上十五米高空的狭窄维修栈桥。
Kira 站在风暴中心，十指纳米丝暴涨成钢铁风暴。
Ron 拔刀怒斩，雷霆之势撕裂苍穹！`,
        directorScenePurpose: '第一集终极情绪高潮。',
        directorEmotionalArc: '从试探到决裂，再到无可挽回的斩击。',
        directorAudienceExperience: '高度紧张窒息的眩晕感。',
        directorPacing: '爆发式高频对攻。',
        directorVisualStrategy: '垂直落差构图，深渊黑洞对比。',
        directorPerformanceDirection: '毫不留情的生死搏杀。',
        directorCameraStrategy: '绕轴环绕轨道运镜。',
        directorLightingStrategy: '暴风雨雷电频闪强光。',
        directorSoundDirection: '金属撞击火花爆鸣，狂风啸叫。',
        directorTransition: '雷暴白光切入下集预告。',
        productionStatus: 'SHOT DESIGNED',
        sortOrder: 3,
        shots: createDemoShots('scene-01-03', 'sc03', 'Ron vs Kira duel', 'High Crane Catwalk'),
        createdAt: '2026-09-02T12:00:00Z',
        updatedAt: '2026-09-03T11:00:00Z',
      },
    ],
    createdAt: '2026-09-01T08:30:00Z',
    updatedAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 'ep-02',
    projectId: 'proj-last-assassin',
    episodeNumber: 2,
    title: 'THE AWAKENED BLADE (古刃苏醒)',
    logline: 'Ron 潜入地下防震金库试图夺回解除控制的频率核心箱，遭遇财阀最高统帅裁决者 Marcus 的重甲截杀。',
    synopsis: '在雨夜道场查明真相后，Ron 突破六十层天台防御，孤身索降至地下百米深处的钛金密室，迎接他的是全副重装黄铜外骨骼的裁决者 Marcus。',
    runtime: '9 分钟 (540s)',
    status: '制作中',
    directorNotes: '重金属机械工业感，从开阔雨夜天台突转入幽闭钛金金库。',
    sortOrder: 2,
    scenes: [
      {
        id: 'scene-02-01',
        episodeId: 'ep-02',
        sceneNumber: 1,
        sceneTitle: 'EXT. ROOFTOP DOJO - DUSK / RAIN (天台雨夜雪松道场潜入 — 傍晚)',
        intExt: 'EXT',
        locationName: 'ROOFTOP DOJO',
        timeOfDay: 'DUSK 黄昏',
        characters: ['RON (浪人)'],
        props: ['ANCIENT KATANA'],
        costumes: ['TACTICAL COMBAT COAT (RON)'],
        storyPurpose: '展现高空潜入身手，俯瞰新京都霓虹云海，定位地下金库的通风入口。',
        emotion: '孤绝、壮阔、暴风雨前的平静。',
        conflict: '避开摩天楼周界的激光防空网。',
        duration: '120s (2m)',
        directorNotes: '桧木地板水镜倒影与赛博霓虹云海形成强烈东方黑色电影韵味。',
        scriptExcerpt: `场次 01. 天台雨夜雪松道场潜入 — 傍晚 (EXT. ROOFTOP DOJO - DUSK)
新京都 60 层悬挑天台。
桧木地面泛着浅浅水光，映照着天际线翻滚的暗红晚霞与霓虹雨幕。
Ron 无声降落在石松盆景旁，目光锁向深渊底部的金库排风主塔。`,
        directorScenePurpose: '视觉奇观建立镜头。',
        directorEmotionalArc: '宏大孤寂。',
        directorAudienceExperience: '大银幕级的视野开阔感。',
        directorPacing: '沉稳优雅慢镜头。',
        directorVisualStrategy: '对称广角构图，水面倒影。',
        directorPerformanceDirection: '身若游龙，步若古松。',
        directorCameraStrategy: '水平平移滑轨 (Dolly lateral)。',
        directorLightingStrategy: '晚霞朱红与全息赛博冷青交织。',
        directorSoundDirection: '悠远风铃声与遥远城市低频轰鸣。',
        directorTransition: '俯冲切入垂直深井。',
        productionStatus: 'SHOT DESIGNED',
        sortOrder: 1,
        shots: createDemoShots('scene-02-01', 'sc0201', 'Ron on Rooftop', 'Rooftop Dojo'),
        createdAt: '2026-09-03T09:00:00Z',
        updatedAt: '2026-09-03T09:00:00Z',
      },
      {
        id: 'scene-02-02',
        episodeId: 'ep-02',
        sceneNumber: 2,
        sceneTitle: 'INT. CYBERNETIC SHRINE VAULT - NIGHT (地下量子神龛金库突破 — 夜)',
        intExt: 'INT',
        locationName: 'SUB-LEVEL VAULT',
        timeOfDay: 'NIGHT 夜晚',
        characters: ['RON (浪人)', 'MARCUS / THE ARBITER'],
        props: ['ANCIENT KATANA', 'CYBERNETIC RELIC BOX'],
        costumes: ['TACTICAL COMBAT COAT (RON)', 'ARBITER CEREMONIAL EXOSUIT'],
        storyPurpose: 'Ron 突破进入核心金库，发现量子核心箱正被 Marcus 启动，双方爆发硬核肉搏。',
        emotion: '震撼、暴力肉搏冲击、高科技冷酷。',
        conflict: 'Ron 灵活拔刀术对决 Marcus 黄铜液压骨骼的霸道纯力量。',
        duration: '210s (3m 30s)',
        directorNotes: '红外线交织切割白雾，每一次重拳轰击都震碎周围防爆玻璃。',
        scriptExcerpt: `场次 02. 地下量子神龛金库突破 — 夜 (INT. CYBERNETIC SHRINE VAULT - NIGHT)
六角形钛合金金库中央，悬浮神龛散发着幽绿脉冲。
裁决者 Marcus 缓缓转过身，黄铜机械臂排气孔喷吐出一股炽热白汽。
MARCUS
幽灵就该安息在坟墓里，Ron。
拳锋呼啸撕破空气，直轰面门！`,
        directorScenePurpose: '重工业力量感与敏捷格斗的对撞。',
        directorEmotionalArc: '遭遇强敌的绝体绝命危机。',
        directorAudienceExperience: '骨骼碎裂级的钝器压迫感。',
        directorPacing: '重拳重击的顿挫感。',
        directorVisualStrategy: '六角对称钛金构图，激光红线切分。',
        directorPerformanceDirection: 'Marcus 如同重型机械人偶，Ron 极速借力打力。',
        directorCameraStrategy: '近距离跟拍拳锋，受击震颤。',
        directorLightingStrategy: '翠绿悬浮光芒与红色警戒频闪。',
        directorSoundDirection: '液压泵充能尖鸣与重拳破风声。',
        directorTransition: '金库重锁被斩断火花飞溅。',
        productionStatus: 'SHOT DESIGNED',
        sortOrder: 2,
        shots: createDemoShots('scene-02-02', 'sc0202', 'Ron vs Marcus in Vault', 'Sub-Level Vault'),
        createdAt: '2026-09-03T10:00:00Z',
        updatedAt: '2026-09-03T10:00:00Z',
      },
      {
        id: 'scene-02-03',
        episodeId: 'ep-02',
        sceneNumber: 3,
        sceneTitle: 'INT. SUB-LEVEL CORE CHAMBER - MIDNIGHT (地下核心控制室决裂 — 午夜)',
        intExt: 'INT',
        locationName: 'SUB-LEVEL VAULT',
        timeOfDay: 'MIDNIGHT 午夜',
        characters: ['RON (浪人)', 'MARCUS / THE ARBITER'],
        props: ['ANCIENT KATANA', 'CYBERNETIC RELIC BOX'],
        costumes: ['TACTICAL COMBAT COAT (RON)', 'ARBITER CEREMONIAL EXOSUIT'],
        storyPurpose: 'Ron 拼死斩断 Marcus 的机械右臂，抢夺量子核心箱并触发自毁程序逃脱。',
        emotion: '生死极限、逃出生天的狂烈节奏。',
        conflict: '在自毁倒计时 60 秒内夺取核心箱脱出。',
        duration: '180s (3m)',
        directorNotes: '全场红光大作，警报蜂鸣震耳欲聋。',
        scriptExcerpt: `场次 03. 地下核心控制室决裂 — 午夜 (INT. SUB-LEVEL CORE CHAMBER - MIDNIGHT)
自毁倒计时警报响彻整个地下中枢。
Ron 借助反作用力凌空拔刀，陨铁刀芒划过一道不可思议的弧线，斩断黄铜机械臂！
抓起悬浮核心箱，冲向紧急逃生井！`,
        directorScenePurpose: '全季高潮大逃亡序曲。',
        directorEmotionalArc: '从向死而生到破局狂奔。',
        directorAudienceExperience: '倒计时迫近的极度心跳过速。',
        directorPacing: '极限狂飙。',
        directorVisualStrategy: '红光爆闪中的高速剪影。',
        directorPerformanceDirection: '负伤极限爆发。',
        directorCameraStrategy: '高速斯坦尼康追逐跟拍。',
        directorLightingStrategy: '警报旋转红光与火花飞溅。',
        directorSoundDirection: '倒计时机械合成女声与警报重音。',
        directorTransition: '烈焰喷涌黑幕。',
        productionStatus: 'SHOT DESIGNED',
        sortOrder: 3,
        shots: createDemoShots('scene-02-03', 'sc0203', 'Ron Escape with Relic Box', 'Sub-Level Vault Core'),
        createdAt: '2026-09-03T11:00:00Z',
        updatedAt: '2026-09-03T11:00:00Z',
      },
    ],
    createdAt: '2026-09-02T08:30:00Z',
    updatedAt: '2026-09-03T09:00:00Z',
  },
];

export const DEMO_CONTINUITY_WARNINGS: ContinuityWarning[] = [
  {
    id: 'cw-demo-1',
    projectId: 'proj-last-assassin',
    sceneId: 'scene-01-01',
    sceneTitle: 'INT. ABANDONED WAREHOUSE - NIGHT',
    shotId: 'shot-01-01-01',
    shotNumber: 1,
    assetType: 'Character',
    assetId: 'char-ron',
    assetName: 'RON (浪人)',
    conflictType: '发型轮廓冲突 (Hair Silhouette)',
    lockedValue: '已锁定主参考 V3: 乌黑微卷纹理短发，两鬓干净利落，打斗中有数缕碎发散落在冷峻额前',
    currentValue: '场次01备忘曾提及“背头大油头”',
    description: '角色 RON 拥有已锁定的主视觉参考 V3（自然微碎发）。生成分镜视频时必须严格遵循 V3 物理发型，防止模型生成油头造成连续性穿帮。',
    severity: 'WARNING',
    category: 'Character',
    status: 'ACTIVE',
    createdAt: '2026-09-04T10:00:00Z',
  },
  {
    id: 'cw-demo-2',
    projectId: 'proj-last-assassin',
    sceneId: 'scene-01-01',
    sceneTitle: 'INT. ABANDONED WAREHOUSE - NIGHT',
    assetType: 'Costume',
    assetId: 'costume-ron-tactical',
    assetName: 'TACTICAL COMBAT COAT (RON)',
    conflictType: '服装磨损度 (Costume Wear State)',
    lockedValue: '已锁定主参考 V1: 崭新隐蔽状态，无破损',
    currentValue: '场次 01 后半段决战已进入高烈度斩击',
    description: '主服装当前为崭新完好状态。在第4分镜斩击之后，建议将服装切换为【BATTLE DAMAGED SUIT (战损版)】以保证左肩撕裂血渍的视听连贯。',
    severity: 'WARNING',
    category: 'Costume',
    status: 'ACTIVE',
    createdAt: '2026-09-04T11:00:00Z',
  },
  {
    id: 'cw-demo-3',
    projectId: 'proj-last-assassin',
    sceneId: 'scene-01-04',
    sceneTitle: 'INT. COLLAPSED CRANE RAILS - NIGHT',
    assetType: 'State',
    assetId: 'char-ron',
    assetName: 'RON (浪人)',
    conflictType: '角色状态连续性校验 (State Continuity)',
    lockedValue: '前一场 (SC03) 状态: [INJURED] (左眉骨流血、风衣撕裂)',
    currentValue: '当前场 (SC04) 状态: [INJURED] 已正确承接',
    description: '系统已成功追踪连续性状态：Ron 在 SC03 受伤后的战损妆造在 SC04 严格继承。',
    severity: 'INFO',
    category: 'State',
    status: 'RESOLVED',
    createdAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 'cw-demo-4',
    projectId: 'proj-last-assassin',
    sceneId: 'scene-01-05',
    sceneTitle: 'EXT. CANAL DRAINAGE SLUICE - DAWN',
    assetType: 'Timeline',
    assetId: 'scene-01-05',
    assetName: 'Timeline',
    conflictType: '故事时间跨度跳跃 (Story Timeline Jump)',
    lockedValue: '前一场故事时段: Day 1 23:30 (深夜)',
    currentValue: '当前场故事时段: Day 2 01:15 (黎明破晓)',
    description: '从深夜暴雨跳跃至黎明破晓，环境照明策略由单束天窗冷光切换为东方地平线晨曦逆光。',
    severity: 'INFO',
    category: 'Timeline',
    status: 'ACTIVE',
    createdAt: '2026-09-04T13:00:00Z',
  },
  {
    id: 'cw-demo-5',
    projectId: 'proj-last-assassin',
    sceneId: 'scene-01-02',
    sceneTitle: 'EXT. INDUSTRIAL DOCKLANDS - NIGHT',
    shotId: 'scene-01-02-shot-4',
    shotNumber: 4,
    assetType: 'Axis',
    assetId: 'scene-01-02-shot-4',
    assetName: 'Shot #4',
    conflictType: '可能越轴冲突 (Possible 180° Axis Break)',
    lockedValue: '分镜 #3 镜头轴线: Screen Right 朝向',
    currentValue: '分镜 #4 运镜轨迹: Left → Right 突变',
    description: '分镜 #3 与分镜 #4 镜头机位跳跃超过 180 度中轴，建议插入中性过切镜头 (Neutral Cutaway) 以防观众视觉迷向。',
    severity: 'WARNING',
    category: 'Axis',
    status: 'ACTIVE',
    createdAt: '2026-09-04T14:00:00Z',
  },
];

// ==============================================================================
// ROUND 4 DEMO DATA: STORY EVENTS & CHECKPOINTS
// ==============================================================================

export const DEMO_STORY_EVENTS: StoryEvent[] = [
  {
    id: 'event-01',
    projectId: 'proj-last-assassin',
    sceneId: 'scene-01-03',
    sceneNumber: 3,
    name: '造船厂纳米陷阱引爆 (Explosion & Trap Ambush)',
    description: 'Kira 引爆预先埋设的高频纳米炸药，仓库承重钢梁坍塌，剧烈火光冲击波震飞 Ron 并撕裂战术风衣。',
    charactersAffected: ['char-ron', 'char-kira'],
    propsAffected: ['prop-katana'],
    locationAffected: '废弃造船厂仓库',
    costumeAffected: ['costume-ron-suit'],
    stateChanges: [
      {
        targetType: 'Character',
        targetId: 'char-ron',
        targetName: 'RON (浪人)',
        fromState: 'NORMAL',
        toState: 'INJURED',
        cause: 'Explosion',
      },
      {
        targetType: 'Prop',
        targetId: 'prop-katana',
        targetName: '龙文大马士革武士刀 (Dragon Katana)',
        fromState: 'NEW',
        toState: 'DAMAGED',
        cause: 'Explosion',
      },
      {
        targetType: 'Location',
        targetId: 'loc-warehouse',
        targetName: '废弃造船厂仓库',
        fromState: 'Clean',
        toState: 'Damaged',
        cause: 'Explosion',
      },
      {
        targetType: 'Costume',
        targetId: 'costume-ron-suit',
        targetName: '暗黑战术隐形风衣',
        fromState: 'NORMAL',
        toState: 'DAMAGED',
        cause: 'Explosion',
      },
    ],
    isApproved: true,
    createdAt: '2026-09-04T11:00:00Z',
  },
  {
    id: 'event-02',
    projectId: 'proj-last-assassin',
    sceneId: 'scene-01-05',
    sceneNumber: 5,
    name: '水闸断罪终结决战 (Final Sluice Confrontation)',
    description: 'Kira 唤醒重装杀手傀儡阻截，Ron 奋力挥刀斩碎装甲核心，刀身应声崩断，自身失血严重濒临虚脱。',
    charactersAffected: ['char-ron'],
    propsAffected: ['prop-katana'],
    locationAffected: '运河排水闸门',
    costumeAffected: ['costume-ron-suit'],
    stateChanges: [
      {
        targetType: 'Character',
        targetId: 'char-ron',
        targetName: 'RON (浪人)',
        fromState: 'INJURED',
        toState: 'BLOODIED',
        cause: 'Fight',
      },
      {
        targetType: 'Prop',
        targetId: 'prop-katana',
        targetName: '龙文大马士革武士刀 (Dragon Katana)',
        fromState: 'DAMAGED',
        toState: 'BROKEN',
        cause: 'Fight',
      },
    ],
    isApproved: true,
    createdAt: '2026-09-04T13:30:00Z',
  },
];

export const DEMO_STORY_CHECKPOINTS: StoryCheckpoint[] = [
  {
    id: 'chk-sc-01',
    sceneId: 'scene-01-01',
    sceneNumber: 1,
    characterStates: [
      { characterId: 'char-ron', characterName: 'RON (浪人)', state: 'NORMAL' },
    ],
    costumeStates: [
      { costumeId: 'costume-ron-suit', costumeName: '暗黑战术隐形风衣', condition: 'NORMAL' },
    ],
    propConditions: [
      { propId: 'prop-katana', propName: '龙文大马士革武士刀', condition: 'NEW' },
    ],
    locationState: {
      locationId: 'loc-warehouse',
      locationName: '废弃造船厂仓库',
      state: 'Clean',
    },
    timelineDate: 'Day 1',
    timelineTime: '22:00',
    importantEvents: ['Ron 潜入造船厂屋顶'],
    openConflicts: ['追查氏族被盗圣物与量子中枢'],
    nextObjective: '突破高窗进入仓库腹地寻找 Kira',
    createdAt: '2026-09-04T10:00:00Z',
  },
  {
    id: 'chk-sc-02',
    sceneId: 'scene-01-02',
    sceneNumber: 2,
    characterStates: [
      { characterId: 'char-ron', characterName: 'RON (浪人)', state: 'NORMAL' },
    ],
    costumeStates: [
      { costumeId: 'costume-ron-suit', costumeName: '暗黑战术隐形风衣', condition: 'NORMAL' },
    ],
    propConditions: [
      { propId: 'prop-katana', propName: '龙文大马士革武士刀', condition: 'NEW' },
    ],
    locationState: {
      locationId: 'loc-warehouse',
      locationName: '码头装卸区与走廊',
      state: 'Clean',
    },
    timelineDate: 'Day 1',
    timelineTime: '22:45',
    importantEvents: ['发现 Kira 布设的陷阱引线'],
    openConflicts: ['敌暗我明，Kira 占领高点机位'],
    nextObjective: '深入中央镜厅直面 Kira',
    createdAt: '2026-09-04T11:00:00Z',
  },
  {
    id: 'chk-sc-03',
    sceneId: 'scene-01-03',
    sceneNumber: 3,
    characterStates: [
      { characterId: 'char-ron', characterName: 'RON (浪人)', state: 'INJURED' },
      { characterId: 'char-kira', characterName: 'KIRA (绮罗)', state: 'NORMAL' },
    ],
    costumeStates: [
      { costumeId: 'costume-ron-suit', costumeName: '暗黑战术隐形风衣', condition: 'DAMAGED' },
    ],
    propConditions: [
      { propId: 'prop-katana', propName: '龙文大马士革武士刀', condition: 'DAMAGED' },
    ],
    locationState: {
      locationId: 'loc-warehouse',
      locationName: '废弃造船厂仓库',
      state: 'Damaged',
    },
    timelineDate: 'Day 1',
    timelineTime: '23:15',
    importantEvents: ['纳米炸药引爆，仓库主梁坍塌，Ron 左臂撕裂伤'],
    openConflicts: ['Ron 受伤且主要退路被火势封锁'],
    nextObjective: '砸穿水泥地漏滑入地下排污主干道',
    createdAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 'chk-sc-04',
    sceneId: 'scene-01-04',
    sceneNumber: 4,
    characterStates: [
      { characterId: 'char-ron', characterName: 'RON (浪人)', state: 'INJURED' },
    ],
    costumeStates: [
      { costumeId: 'costume-ron-suit', costumeName: '暗黑战术隐形风衣', condition: 'DAMAGED' },
    ],
    propConditions: [
      { propId: 'prop-katana', propName: '龙文大马士革武士刀', condition: 'DAMAGED' },
    ],
    locationState: {
      locationId: 'loc-warehouse',
      locationName: '地下工业排污隧道',
      state: 'Flooded',
    },
    timelineDate: 'Day 1',
    timelineTime: '23:45',
    importantEvents: ['Ron 涉水逃脱机械猎犬追捕'],
    openConflicts: ['伤口受污染感染加剧，体力严重透支'],
    nextObjective: '游至运河泄洪闸门寻找生路',
    createdAt: '2026-09-04T12:30:00Z',
  },
  {
    id: 'chk-sc-05',
    sceneId: 'scene-01-05',
    sceneNumber: 5,
    characterStates: [
      { characterId: 'char-ron', characterName: 'RON (浪人)', state: 'BLOODIED' },
    ],
    costumeStates: [
      { costumeId: 'costume-ron-suit', costumeName: '暗黑战术隐形风衣', condition: 'DAMAGED' },
    ],
    propConditions: [
      { propId: 'prop-katana', propName: '龙文大马士革武士刀', condition: 'BROKEN' },
    ],
    locationState: {
      locationId: 'loc-warehouse',
      locationName: '运河排水闸门',
      state: 'Damaged',
    },
    timelineDate: 'Day 2',
    timelineTime: '01:15',
    importantEvents: ['决战断刃，击退追兵，黎明初现'],
    openConflicts: ['佩刀崩碎，圣物被送往新京都黑市'],
    nextObjective: '潜入黑市安全屋寻找隐退神匠修刀并疗伤',
    createdAt: '2026-09-04T13:30:00Z',
  },
];

